# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0003_auto_20160922_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('invite_code', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='reg_id',
            new_name='invite_code',
        ),
    ]
