# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0008_auto_20160926_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
