# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0009_auto_20160926_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitecode',
            name='used',
        ),
        migrations.AddField(
            model_name='invitecode',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
