# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0010_auto_20160926_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitecode',
            name='email',
        ),
    ]
