# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0011_remove_invitecode_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitecode',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
