# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0012_invitecode_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitecode',
            name='leader',
            field=models.CharField(default='old', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
