# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0013_auto_20160926_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitecode',
            name='email',
            field=models.CharField(default='old', max_length=128),
            preserve_default=False,
        ),
    ]
