# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0014_invitecode_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitecode',
            name='sent_dtg',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
