# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0017_invitecode_sent_dtg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitecode',
            name='sent_dtg',
        ),
    ]
