# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0020_remove_invitecode_sent_dtg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('module', models.FileField(upload_to='modules/')),
                ('upload_dtg', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
