# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0021_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='owner',
            field=models.CharField(default='old', max_length=255),
            preserve_default=False,
        ),
    ]
