# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0023_modules_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='storage',
            field=models.CharField(default='old', max_length=32),
            preserve_default=False,
        ),
    ]
