# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0024_modules_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='team',
            field=models.CharField(default='old', max_length=255),
            preserve_default=False,
        ),
    ]
