# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0025_userprofile_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location_city',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location_country',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location_state',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
