# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0026_auto_20161011_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulesStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dlp.Modules')),
            ],
        ),
    ]
