# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0027_modulesstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulesstatus',
            name='dtg',
            field=models.DateTimeField(auto_now_add=True, default='2001-01-01 12:00:00'),
            preserve_default=False,
        ),
    ]
