# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0028_modulesstatus_dtg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulesstatus',
            name='dtg',
        ),
    ]
