# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0029_remove_modulesstatus_dtg'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulesstatus',
            name='dtg',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
