# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 19:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0030_modulesstatus_dtg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulesstatus',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlp.Modules'),
        ),
        migrations.AlterField(
            model_name='modulesstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
