# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0033_messageboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageboard',
            name='parent',
            field=models.TextField(default='old', max_length=32),
            preserve_default=False,
        ),
    ]
